Fix compile for UE5.4 (#104)
* Fix compile, due to newly introduced pure virtual UpdatePackageModificationStatus not implemented in subclass

* Fix compile due to 5.4 API changes

* Fix C4702 dead code by adjusting  #if conditions.

* Fix "error C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'"